version: "3"
services:
  webapp:
    image: nginx:1.9-alpine
    volumes: 
      - ./nginx-conf:/etc/nginx/conf.d/
      - ./:/app
    networks:
      - web
    ports: 
      - 9999:80
  php-fpm:
    image: bitnami/php-fpm
    networks:
      - web
    volumes:
      - ./:/app
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: assignment
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - web
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    networks:
      - web

networks: 
  web:
    driver: bridge

  
